CREATE DATABASE Parcial01;

USE Parcial01;

CREATE TABLE Deporte (
    ID_DEPORTE INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(50) NOT NULL
);

INSERT INTO Deporte (DESCRIPCION) VALUES 
('Futbol'),
('Básquet'),
('Tenis');

CREATE TABLE Partido (
    ID_PARTIDO INT PRIMARY KEY IDENTITY(1,1),
    ID_DEPORTE INT FOREIGN KEY REFERENCES Deporte(ID_DEPORTE),
    EQUIPO_LOCAL VARCHAR(100) NOT NULL,
    EQUIPO_VISITANTE VARCHAR(100) NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FECHA_PARTIDO DATETIME NOT NULL,
    MARCADOR_LOCAL INT DEFAULT 0,
    MARCADOR_VISITANTE INT DEFAULT 0
);